version: "3.9"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
  # server:
  #   container_name: server
  #   image: server:latest
  #   entrypoint: python3 /main.py
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=INFO
  #   networks:
  #     - testing_net
  #   volumes:
  #     - ./server/config.ini:/config.ini
  #     - ./shared:/shared

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
